controller_manager:
  ros__parameters:
    update_rate: 225  # Hz

    kr360_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

kr360_arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6

    state_publish_rate: 200.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: false
    open_loop_control: true
    allow_integration_in_goal_trajectories: true
    allow_nonzero_velocity_at_trajectory_end: true

    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.6
      joint_a1:
        trajectory: 0.2
        goal: 0.1
      joint_a2:
        trajectory: 0.2
        goal: 0.1
      joint_a3:
        trajectory: 0.2
        goal: 0.1
      joint_a4:
        trajectory: 0.2
        goal: 0.1
      joint_a5:
        trajectory: 0.2
        goal: 0.1
      joint_a6:
        trajectory: 0.2
        goal: 0.1

joint_state_broadcaster:
  ros__parameters:
    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6
